### ISSUE TITLE
Entwicklerflyer gestalten

### ISSUE THREAD

**Issue by SarahSauer** [typearea/projectmanagement#10]
selbst ausdrucken, auf eine DIN A4 Seite 3 Stück

**Comment by ghost** [comment]
der Text ist unter #5 verlinkt, das was in der <tagcloud> steht, als graue Tag-Kästchen gestalten und als Cloud anordnen.

**Comment by Dembelo-Jessica** [comment]
Ich arbite ja noch dran, dieses System zu verstehen, daher hab ich den Text des Flyers jetzt hierher kopiert, um dazu zu sagen, was ich sagen wollte. Wenn das auch anders gegangen wäre, lasst es mich wissen, ich konnte da nicht rausfinden, wie/ob ich kommenteiren oder ändern kann unter dem Link, der oben gegeben war. 

Also Folgendes: Es fehlen "zu"s:

Hast du Lust, moderne Software nach allen Regeln der Kunst zu entwickeln?
Neue Techniken aus[zu]probieren, die in Blogartikeln immer so innovativ wirken?
Dinge endlich mal RICHTIG [zu] machen – und nicht so, wie es in der Firma schon seit Jahren läuft?

Wir wollen Dembelo als modulare, robuste und moderne Software entwerfen, die uns auch in Zukunft die Möglichkeit gibt, durch gute Wartbarkeit auf dem aktuellen Stand der Technik zu bleiben.

<tagcloud>
Open Source, PHP, OOP, github, Unit Tests, travisCI, Coding Standards, PHPUnit,
Clean Code, Twitter Bootstrap, Refactoring, Code Coverage, github/waffle.io, CodeSniffer, Symfony, Webix, Feature Branches, Composer, Doctrine, sass, Selenium-Tests
</tagcloud>

github.com/typearea/dembelo - waffle.io/typearea/dembelo

Im Übrigen, da hier steht "moderne" Softwre, möchte in anregen, doch eine serifenlose, schlanke Schrift zu nehmen, um das auch optisch darzustellen.

**Comment by Dembelo-Jessica** [comment]
Was ist hieraus eigentlich geworden? Im Prinzip war es doch fast fertig, oder? Gb mal jemand laut!

**Comment by SarahSauer** [comment]
Gute Frage - wenn es noch gewünscht ist, könnte ich das bis nächste Woche in Angriff nehmen.

**Comment by SarahSauer** [comment]
@michaelgiesler @tinagiesler @KatharinaMarks 
Hab jetzt schnell einen Entwurf zusammengebastelt: https://github.com/typearea/projectmanagement/blob/master/Flyer/Entwicklerflyer-Entwurf1.pdf

**Comment by michaelgiesler** [comment]
Das sieht jetzt eher nach Stellenangebot aus. Um falsche Erwartungen zu vermeiden, sollte klar werden, dass wir ein Open Source-Projekt auf der Suche nach freiwilligen Mitstreitern sind.

**Comment by SarahSauer** [comment]
Zweiter Entwurf: https://github.com/typearea/projectmanagement/blob/master/Flyer/Entwicklerflyer-Entwurf2.pdf

**Comment by michaelgiesler** [comment]
jo, meinetwegen.
