### ISSUE TITLE
Wie beweise ich meine Urheberschaft? ergänzen

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#101]
Um den Artikel für normalsterbliche verständlicher und um 5 Sätze länger zu machen würde ich dich noch bitte für die möglichen "Gegenbeweise" Beispiele zu formulieren, wie ein solcher Beweis im Streitfall aussehen könnte.

Also was ich z.B. als Sachbeweis beibringen könnte um zu beweisen, dass der andere nicht der Urheber ist.

**Comment by KatharinaMarks** [comment]
@tinagiesler you've got mail. :)

**Comment by ghost** [comment]
@Dembelo-Jessica ist im Blog als Entwurf, bitte korrekturlesen, habe das Gefühl, dass ein zwei Satzzeichen tektisch günstig gesetzt werden könnten, um die Betonung zu verbessern, aber das überlasse ich dir.
Kann dann direkt veröffentlich werden alles andere ist vorbereitet.

**Comment by Dembelo-Jessica** [comment]
Ist korrigiert, steht bereit.
