### ISSUE TITLE
future!publish eruieren

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#102]
ist schon im Januar, und wenn ich mich richtig erinnere sau teuer.

**Comment by KatharinaMarks** [comment]
550€ für ein reguläres Ticket, plus Anfahrts- und Übernachtungskosten. Und von den 37 angebotenen Vorträgen/Workshops sind, soweit ich das beurteilen kann, gerade mal 3 interessant für uns. Natürlich können wir diese Veranstaltung für Werbezwecke nutzen, aber der praktische Nutzen wird sehr gering sein für den unverhältnismäßigen Aufwand.
