### ISSUE TITLE
http://www.booknerds.de eruieren

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#103]

**Comment by KatharinaMarks** [comment]
Das ist ein mittlerweile bekannteres und anerkanntes Indie Magazin, dessen Inhalte Rezensionen über alles Mögliche sind.
Meine Frage daher: wollen wir von denen rezensiert werden, um unseren Bekanntheitsgrad zu steigern? Oder wohin zielt dieser Issue?

**Comment by ghost** [comment]
Zu beurteilen wäre ob wir überhaupt für eine Rezension in Frage kommen und wenn ja wann, deiner zusammenfassung nach würde ich schätzen, dass eine Rezension hier erst bei Betastart der Software relevant wird. So ein Issue wäre also abgeschlossen, wenn man rausgefunden hat, was man mit der Seite/Firma/etc. anfangen kann und dies im Projektmanagementwiki hinterlegt hat. Unter Kooperationen würde ich jetzt den Abschnitt Magazine anlegen und den Unterabschnitt nach Betastart und dort den Link und ein paar Eckdaten hinterlegen.

**Comment by ghost** [comment]
Habe die Struktur angelegt: https://github.com/typearea/projectmanagement/wiki/Potenzielle-Kooperationen#magazine
Kannst du @KatharinaMarks URL und Eckdaten hinterlegeen? Ein erklärender Satz reicht. Dann ist diese Aufgabe auch erfüllt und kann direkt unter Done.

**Comment by KatharinaMarks** [comment]
Soll ich vorher eine Anfrage an booknerds machen und unser Projekt vorstellen, um tatsächlich rauszufinden, ob sie uns rezensieren würden, wenn es soweit ist? Von der Seite her ist nicht ersichtlich, ob sie auch digitale Literatur rezensieren.

**Comment by ghost** [comment]
Nö, Kontaktaufnahme erst wenn wir wirklich was zu zeigen haben, sonst laufen wir als Spam.
