### ISSUE TITLE
Open Access Artikel  lesen und kommentieren

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#105]
https://www.buchreport.de/2016/12/07/open-access-ist-das-beste-mittel-gegen-e-book-piraterie/

Artikel Lesen, Gedanken auf das Dembelo-Konzept reflektieren und einen Kommentar in unserem Blog schreiben, wie auch eine Stellungnahme bei br hinterlassen.

**Comment by ghost** [comment]
Nicht schlagen, ist schon für den 22.12. geplant. bitte bis dahin korrekturlesen sind nur zwei Absätze. @Dembelo-Jessica

**Comment by Dembelo-Jessica** [comment]
freigegeben
