### ISSUE TITLE
Landingpage freischalten

### ISSUE THREAD

**Issue by SarahSauer** [typearea/projectmanagement#11]
sobald Patreon & waszulesen.de Inhalt hat, freischalten

**Comment by Dembelo-Jessica** [comment]
Dazu notwendig, ad darauf verlinkt wird:

– Betaversion 
– Patreon 

Alternativ bei der Betaversion einen Hinweis, dass es noch keine gibt.

**Comment by Dembelo-Jessica** [comment]
Wir haben eine Übergangsgraphik für die Beta.

**Comment by Dembelo-Jessica** [comment]
Welche Adresse soll die Seite nachher haben?

**Comment by ghost** [comment]
Landingpage auf www.dembelo.de, der blog auf www,dembelo.de/blog

**Comment by ghost** [comment]
Rechts vor der Pfeil nach oben ist, bitte auch einen Pfeil nach unten
Ja, ich halte die potenziellen Besucher für Idioten.

Und wie wäre es, wenn wir statt des Links auf die nicht forhandene Beta einen Link zum Newsletter schalten mit dem Text, "Sagt mir bescheid, wenn es los geht." ?

**Comment by Dembelo-Jessica** [comment]
Das mit dem Pfeil nach unten ist totaler Unsinn. Ich seh heute Abend nach, ob das geht, aber wenn es irgendwie umständlich ist -> vergiss es.
Das mit dem Newsletter ist gut.

**Comment by ghost** [comment]
Was ist hierfür noch explizit nötig?
- [x] Piwik Code einbinden, siehe Issue #27 
- [x] Impressum schreiben, machst du da bitte ein Issue zu? Oder gibt es da eins?
- [x] Was zu lesen Icon auf Newsletter verlinken und Text darunter ändern

Noch was?

**Comment by Dembelo-Jessica** [comment]
- [x] Bei Online-Schaltung Umleitungen einrichten von den abweichenden Adressen, die schon auf den Visitenkarten stehen. Wird erledigt.

**Comment by Dembelo-Jessica** [comment]
ist erledigt
