### ISSUE TITLE
Crowdfunding Kampagne

### ISSUE THREAD

**Issue by KatharinaMarks** [typearea/projectmanagement#111]
1. Patreon Seite überarbeiten (englischsprachige Plattform -> englischsprachige Crowd)
2. http://www.nextbookup.de/crowdfunding-verlag/ eruieren
3. https://www.startnext.com/pages/correctiv#projects eruieren
4. ggf. weitere Plattformen eruieren?
5. Haben wir ein Pitch-Video?

**Comment by Dembelo-Jessica** [comment]
zu 1) Eine englischsprachige Seite zu haben, bringt uns erstmal nichts, da unsere Angebote alle auf Deutsch sind, wir also auch nur deutschsprachige Interessenten ansprechen.

zu 4) Ist meines Wissens gemacht worden. Andere Plattformen waren allerdings noch nicht so etabliert.

zu 5) Wir haben kein Pitch-Video. Dazu muss erst das Konzept stehen. Und wir müssen uns entschieden haben, ob und in welcher Form wir mit rowdfunding-Kampagnen arbeiten wollen.

**Comment by SarahSauer** [comment]
zu 1) Da würde ich auch erstmal auf Deutsch bleiben. Es gibt da auch eine deutsche Crowd - ein paar deutsche Projekte werden auch recht erfolgreich unterstützt (z.B. https://www.patreon.com/Hoaxmaster, https://www.patreon.com/laburrini). Das Problem ist eher, dass wir bisher keine Fanbase haben, die wir zu Patreon locken könnten. Dafür müssen wir erstmal sichtbarer sein und am besten schon Inhalte haben, mit denen wir Fans finden können (vielleicht sollten wir dafür die Texte, die wir bisher auf fanfiktion.de haben, stärker bewerben)

**Comment by michaelgiesler** [comment]
Versucht mal, pro Punkt ein Issue anzulegen, damit nicht mehrere Diskussionsstränge in einem Issue vermischt werden.

1) Da wir keinen englischen Muttersprachler haben, den deutschen Markt besser kennen als den englischsprachigen, und unsere Zeit ohnehin schon zu knapp ist, empfiehlt sich eine Konzentration auf das nächstliegende, nämlich den deutschsprachigen Raum.

**Comment by SarahSauer** [comment]
Ich habe jetzt für 1, 4 und 5 eigene Issues erstellt ( #127, #128, #129 )- 2 und 3 habe ich mir angesehen und sind meines Erachtens für uns uninteressant, da bei 2 seit über einem Jahr nichts mehr passiert ist und 3 sich nur an Journalisten richtet.
