### ISSUE TITLE
Dembelogedanken: Textproduktion Blogartikel gegenlesen

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#113]
Ich versuche ja gerade Dembelo zu erklären und möchte dies in Einzelaspekten tun, das hier wäre so das erste Schlagwort, das mir eingefallen ist und das ich in Text gefasst habe.

**Comment by Dembelo-Jessica** [comment]
fertig

**Comment by ghost** [comment]
@Dembelo-Jessica Kann er so online? Wenn ja, bitte entsprechend bestätigen, wenn nein, bitte Korrektur-issue anlegen und hier verlinken. Danke!

**Comment by Dembelo-Jessica** [comment]
Ja, fertig sollte heißen "kann online".
