### ISSUE TITLE
Kommentar: Über Komfortzone und Erfolg Blogartikel gegenlesen

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#114]
Aufbauend auf #113 ist dieser Artikel entstanden, bitte gegenlesen bewerten und ggf. entscheiden wie die beiden Artikel zueinander stehen sollen.

**Comment by Dembelo-Jessica** [comment]
Es bleibt etwas schwammig, inwieweit der Artikel mit dem Blogeintrag zu tun hat, außer als Denkanstoß. was davon stammt denn aus dem Artikel? Das könnte man noch deutlicher rausarbeiten und auch mehr Bezug zur Überschrift herstellen. Warum ist es denn jetzt besser, an etwas zu schreiben, was man nicht liebt?

**Comment by ghost** [comment]
Warum ist es denn jetzt besser, an etwas zu schreiben, was man nicht liebt? <- das steht in dem Artikel, den ich vorab verlinke, daher würde ich das nicht erneut wiederholen wollen.
