### ISSUE TITLE
gemeinsames Schreiben - Testrunde

### ISSUE THREAD

**Issue by KatharinaMarks** [typearea/projectmanagement#119]
- ein vorgegebenes Setting
- verteilte Rollen
- kleine Absätze für direkte Interaktion
- Plattform: Skype/Line?

**Comment by Dembelo-Jessica** [comment]
Ich schlage den Chat im Wiki vor. Vorteil: Die Ergebnise sind ohne Mehraufwand protkolliert, das geht da nämlich automatisch.
