### ISSUE TITLE
Vorproduzieren von 15 Texten (4 Ebenen) als Startcontent für waszulesen

### ISSUE THREAD

**Issue by KatharinaMarks** [typearea/projectmanagement#120]
- [ ] Ebene 1: Ausgangstext mit insgesamt 2 Verzweigungen
- [ ] Ebene 2: zwei Texte mit insgesamt 4 Verzweigungen
- [ ] Ebene 3: vier Texte mit insgesamt 8 Verzweigungen
- [ ] Ebene 4: acht Texte mit insgesamt 16 Verzweigungen

**Achtung:** Vorfinanzierung iSd. Projektkonzepts findet dann erst ab Ebene 5 statt. Kostenabdeckung für Ebene 1-4 muss anderweitig stattfinden (Fördermittel etc.).

**Comment by SarahSauer** [comment]
machen wir dieses Jahr ohnehin nicht mehr …
