### ISSUE TITLE
Pinterest

### ISSUE THREAD

**Issue by Dembelo-Jessica** [typearea/projectmanagement#122]
Sarah hat es im Marketing-Konzept angesprochen:
Wir müssten wissen, ob wir Pinterest ungefährdet von rechtlichen Problemen weiterhin nutzen können.

**Comment by ghost** [comment]
Vergleiche Chefentscheid: https://github.com/typearea/projectmanagement/wiki/Konzept-f%C3%BCr-Social-Media-Marketing

Da wir keine klare Anwendung haben und damit keinen definierten Nutzen lassen wir das Thema einfach bleiben.
