### ISSUE TITLE
Frage Blogartikel

### ISSUE THREAD

**Issue by Dembelo-Jessica** [typearea/projectmanagement#123]
Du kennst Dich doch aus: Für welche Uhrzeiten/Wochentage sollten wir unsere Blogartikel planen? Sollten wir in unser Marketing-Konzept aufnehmen.

Ich plane nämlich nachher einen Artikel und habe mich gefragt, ob es sinnvoll ist, etwas aufs WE zu legen oder eher nicht.

**Comment by SarahSauer** [comment]
Ich wollte mir gerade mal die FB Statistik von Dembelo ansehen - aber anscheinend gibt es da die Ansicht, wann die Fans am häufigsten online sind, nicht mehr. Zumindest konnte ich sie nicht finden.
Generell ist Wochenende aber eine gute Zeit zum Posten, weil die Leute dann auch Zeit zum Lesen haben. Am besten Vormittags, damit die Leute den Blog gleich in ihrem Feed haben, wenn sie nach dem Frühstück oder so anfangen die abonnierten Blogs zu lesen. Generell ist daher morgens für Blogs gut. Das Problem momentan dürfte nur sein, dass wir vermutlich noch nicht viele Leute haben, die tatsächlich über den Feed lesen (kann man das irgendwie nachhalten?) und wir Leute daher über Facebook und Twitter anlocken müssen. 
Auf Twitter sollte am besten öfters gestreut werden, da das sehr vergänglich ist - da kenne ich passende Plugins für, kümmere ich mich noch drum. Facebook ist vermutlich nachmittags/abends am sinnvollsten, da die Leute nach der Arbeit eher Zeit haben, auf Facebook zu surfen und Blogartikel zu lesen (Abends zwischen 18-20 Uhr war auch die Zeit, wo meine Fans am häufigsten online waren, als ich das vor ein paar Monaten mal nachgeguckt hatte). Da wäre es eventuell eine Überlegung wert, nicht mehr automatisch auf Facebook zu streuen, sondern das zur quasi Prime Time manuell zu machen.

**Comment by ghost** [comment]
Die Buchbranche liest in der Woche zwischen 8 und 10 Uhr früh, am meisten Twitter oder Facebook. Das ist die Zeit die ich für t:a-Artikel immer hatte, die Lesen halt beim ersten Kaffee im Büro, für ab 10 haben sie termine und um 18 Uhr Feierabend.

**Comment by Dembelo-Jessica** [comment]
Dann sollten wir also auf Twitter morgens/vormittags schalten und bei FB nachmittags ab 17-18 Uhr. Richtig?
Dann sollten wir das ab sofort so machen. Da müsste sich nur noch einspielen, wer darauf achtet, dass FB einzeln angeschubst wird. Der Autor des Artikels?

**Comment by Dembelo-Jessica** [comment]
Ok, Autor kümmert sich drum.
