### ISSUE TITLE
Bezug auf verlinkte Artikel

### ISSUE THREAD

**Issue by Dembelo-Jessica** [typearea/projectmanagement#124]
bezieht sich auf Issue #114 (Kommentar: Über Komfortzone und Erfolg)

Problem ist Folgendes: Wenn ein Artikel verlinkt ist, ohne den man den Inhalt unseres Artikels nicht in Gänze versteht, dann schicken wir die Leute im Prinzip erst weg, damit sie den anderen Artikel lesen, damit sie später wiederkommen und unseren Artikel lesen.

Meine Frage: Ist das sinnvoll? Wir können ja nicht unbedingt davon ausgehen, dass alle die betreffenden Artikel schon kennen, auf denen unsere Gedankengänge beruhen. Wenn der Bezug so eng ist und die Quelle, die den Gedanken angestoßen hat, so "obskur", soll heißen nicht allgemein bekannt, halte ich es für sinnvoller, die Passagen in Zitatform oder als Paarphrase (je nachdem) zu wiederholen, auf die man sich bezieht.
Oder wahlweise nicht den Titel des verlinkten Artikels zu nennen, sondern anders zu verlinken, um nicht (durch Nennung der verlinkten Artikelüberschrift) ein Thema reinzubringen, auf das man dann eigentlich nur am Rande eingeht, wenn überhaupt. Das irritiert beim Lesen ein wenig.

**Comment by ghost** [comment]
Aktuell haben unsere Quellartikel mehr Leser als unsere Artikel, durch einen Kommentar entsteht ein Pingback in den Kommentaren der Quelle, von dem aus Leser zu uns kommen, die kennen dann den Artikel schon und diese Richtung ist auch das erklärte Ziel solcher Kommentare
Für unsere Leute ist der Dembelobezug wichtiger, sie lesen was es mit Dembelo zutun hat und können sich dann mit dem Quellartikel beschäftigen.

**Comment by SarahSauer** [comment]
Bei unseren momentanen Besuchszahlen würde ich mich Tinas Argumentation anschließen – die Wahrscheinlichkeit, dass wir Leser über den Link verlieren ist eher gering. Wer unser Blog aufruft, tut das momentan, weil ihn unser Projekt interessiert, wird entsprechend auch wieder in den Artikel zurückkehren.

**Comment by ghost** [comment]
Ich würde dieses Issue also mit folgendem Ergebniss abschließen: Wir haben nun das Label: Blogkommentar. Das markiert Texte, die wir sozusagen nur zur Vernetzung Kommentieren wollen, weil sie für uns relevant sind, aber keinen eigenen Artikel im dembelo-Blog brauchen. Dabei schreiben wir den Kommentar entweder in unserem Blog, wenn die Quelle auch ein Blog ist und entsprechend verlinkt, oder in die Kommentare der Quelle. Für das zweitere brauchen wir Accounts, die eindeutig zu Dembelo zurückführen, das übergebe ich mal an @SarahSauer als Social-Media-Frau. Vergleiche #131

**Comment by ghost** [comment]
Reviewauftrag: Im Wiki nachtragen. gerne unter "offene Fragen"
