### ISSUE TITLE
Patreon-Seite überarbeiten

### ISSUE THREAD

**Issue by SarahSauer** [typearea/projectmanagement#127]
Sobald wir unser Konzept noch einmal abgeklopft haben (vgl. #115 ), sollten wir den Text noch einmal überarbeiten
(entstanden aus #111 )

**Comment by ghost** [comment]
Entsprechende Texte in Deutsch und Englisch findet ihr in diesem Commit: 3ada9733ebaa383eb4b938f3bc909887f61ba016
