### ISSUE TITLE
Daten für Kommentarkonten hinterlegen

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#131]
Damit wir beim Börsenblatt oder auf ähnlichen Plattformen in Dembelos Namen Kommentieren können sollten wir immer die selben Daten für so etwas anlegen. Damit wir nicht in jedem Blog/Magazin je drei oder vier Konten haben.

**Comment by SarahSauer** [comment]
Daten sind im internen Wiki ergänzt
