### ISSUE TITLE
Einen Artikel über die Texte bei ff.de schreiben

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#138]
Wir sollten auf die Texte und den neuen Account bei ff.de verweisen, am besten am 24.12. als Weihnachtsgeschenk sozusagen.

Indigo? Schaffen wir bis dahin auch den Tem Text online zu bekommen?

**Comment by Dembelo-Jessica** [comment]
Beim Tem-Text war für dich noch eine Frage hinterlegt, glaube ich. Wenn das geklärt ist, kein Problem.
https://github.com/SarahSauer/waszulesen/issues/7

**Comment by Dembelo-Jessica** [comment]
Tem ist online, kannst mit dem ARtiel loslegen, @tinagiesler .

**Comment by ghost** [comment]
Artikel ist geschrieben, ist entsprechend kurz, aber das ist ja nicht schlimm. Die Verteilertexte müssten noch und eine Kopfgrafik aus dem Gattlandposter wäre cool. Schafft das wer anders? meine Rechte Hand ist gerade Rheuma und Bruchbedingt außer gefächt.
