### ISSUE TITLE
Frage zu ff.de-Text

### ISSUE THREAD

**Issue by Dembelo-Jessica** [typearea/projectmanagement#139]
Einer der Texte steht auf "fertiggestellt" und einer auf "in rbeit". Absicht? Im Prinzip sind ja all diese Texte in sich fertig.

**Comment by ghost** [comment]
Nein, der eine der nicht auf fertiggestellt steht ist der Teil mit Gregor und Ellan, wo das erste Kapitel zwei Optionen hat die beide in direkter zeitlicher Folge zum Elternelement stehen. Da würde die zweite Option als drittes Kapitel eingefügt werden und ert dann wäre dieses Element abgeschlossen, die beiden anderen Texte sind abgeschlossen. 

Wir können den ersten Text aber auch nicht vorläufig auf abgeschlossen stellen, weil es sonst 60 Tage dauert bis wir wieder ein Kapitel einfügen können.
