### ISSUE TITLE
FF.de + "Mitmachgeschichten"

### ISSUE THREAD

**Issue by Dembelo-Jessica** [typearea/projectmanagement#140]
Lest euch mal den Punkt "Mitmachgeschichten" unter der Rubrik "Verbotenes" beim Erstellen einer neuen Geschichte durch.

Zählt das Wählen einer Fortsetzung wohl nach FF.de-Politik als Organisation von Handlung und Figuren der Geschichte durch Reviews?

**Comment by ghost** [comment]
Nein, weil es keine Diskussionsketten sind und das Review auch Feedback zum Text enthält. Das heißt jeder Leser, liest, gibt Feedback und trift seine Wahl. Weiter geht es in einer neuen vollständigen Geschichte. Was ff.de mit dem Verbot vermeiden will sind Geschichten bei denen auf ein 200 Wort Kapitel 50 Reviews mit Wünschen und Diskussionen kommen. Daher veröffentlichen wir ja fast jeden Knoten als eigenen Text und nicht alle Texte in einer Geschichte.
