### ISSUE TITLE
Buffer nachoptimieren

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#141]
Kann man in dem Tool sagen, dass bestimmte Artikel nicht wiederholt gestreut werden sollen?

z.B. der Wir werden 1 Jahr Artikel, sollte nicht mehrmals gestreut werden.

**Comment by SarahSauer** [comment]
Einzelne Kategorien und Artikel lassen sich ausschließen – aktuell wird die Kategorie Rückblick nicht mehr geteilt und ein paar andere zeitgebundene Artikel.
