### ISSUE TITLE
Themen für das Autorencamp zusammentragen

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#143]
Themenvorschläge zusammentragen und auf allen Ecken rumschicken.

**Comment by SarahSauer** [comment]
Übersicht der bisherigen Themen auf https://github.com/typearea/projectmanagement/wiki/Autorencamp-2017-im-UPH

Die FB Umfrage wurde bisher in den Facebook-Gruppen "Nächtliche Schreibwerkstatt" und "Autoren Netzwerk", im Autorenforum "Tintenzirkel" und über twitter geteilt.
