### ISSUE TITLE
Wo kann man noch Werbung fürs Autorencamp machen?

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#145]
Wir haben noch 1000 Flyer, wo könne wir sie noch verteilen?

**Comment by ghost** [comment]
Aushängebretter 
- [ ] an der Uni Bochum ( @KatharinaMarks, @SarahSauer )
- [ ] an der Uni Essen ( @ich )
- [x] an der Uni Münster ( @Dembelo-Jessica )
- [x] an der Uni Paderborn
- [ ] in Bibliotheken

Persönliche Mails ggf. mit Bitte um Weitergabe:
- [x] VHS Essen: http://www.vhs-essen.de/hansguentherweber.htm
- [x] UPH Mailingliste
- [x] VHS Bochum: vhs@bochum.de
- [x] VHS Münster

**Comment by michaelgiesler** [comment]
Das Kulturbüro bringt einen Literaturkalender "Literatur in Essen" raus (https://t.co/vcHIo0hQYC) Da sollten wir vertreten sein.

**Comment by SarahSauer** [comment]
Ich habe eine E-Mail an die beiden VHS und an die Zuständige von "Literatur in Essen" geschickt
