### ISSUE TITLE
Für den 30.04 den E8 fürs Brunch reservieren.

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#159]
Den Autorenbrunch am 30.04. im E8 können wir als eigene Veranstaltung bewerben. Und wenn wir Essen buchen, können wir auch Räume in der Gastro reservieren. Der Tisch in E8 wäre dafür richtig cool.

**Comment by SarahSauer** [comment]
Hast du das nicht am Dienstag erledigt?
