### ISSUE TITLE
RSS Button für Blog

### ISSUE THREAD

**Issue by SarahSauer** [typearea/projectmanagement#169]
Damit man uns problemlos abonnieren kann, sollten wir einen Button dafür irgendwo sichtbar im Blog haben.

**Comment by michaelgiesler** [comment]
im HTML der Landingpage müssen diese beiden Zeilen rein:

<link rel="alternate" type="application/rss+xml" title="Dembelo &raquo; Feed" href="https://www.dembelo.de/blog/feed/" />
<link rel="alternate" type="application/rss+xml" title="Dembelo &raquo; Kommentar-Feed" href="https://www.dembelo.de/blog/comments/feed/" />

**Comment by Dembelo-Jessica** [comment]
Erledigt
