### ISSUE TITLE
Retrospektive zum Schreibprozess

### ISSUE THREAD

**Issue by SarahSauer** [typearea/projectmanagement#171]
Sobald der neue Knoten steht, sollten wir in einer Retrospektive besprechen, was geklappt hat, was nicht und was sich noch optimieren ließe.

**Comment by michaelgiesler** [comment]
Das Schreiben hat nicht funktioniert, weil wir zu wenig Arbeitszeit auf zu viele Aufgaben haben.

**Comment by ghost** [comment]
Ich habe das was wir bisher rausgefunden haben und wie wir es aktuell als realisierbar und effektiv halten zusammengefasst: 
https://www.dembelo.de/blog/wp-admin/post.php?post=1036&action=edit
Bitte draufschauen ob das so reicht und ggf. lektorieren.
