### ISSUE TITLE
Owesys reparieren

### ISSUE THREAD

**Issue by SarahSauer** [typearea/projectmanagement#173]
Registrierung funktioniert nicht; Verlinkungen/Plugins ebenfalls nicht

**Comment by Dembelo-Jessica** [comment]
fertig bis Juni
bitte Link hier:

**Comment by michaelgiesler** [comment]
SSH-Zugang an Jessica

**Comment by michaelgiesler** [comment]
gucken, welche Extension kaputt gegangen ist.

**Comment by michaelgiesler** [comment]
Habe Owesys auf die aktuelle mediawiki-Version (1.28.2) aktualisiert und bei der Gelegenheit das Registrierungsformular gefixt.

Was ist denn sonst noch kaputt?

**Comment by ghost** [comment]
die Übersichtsseiten der Szenarien: https://www.owesys.org/index.php/Die_Steine_im_Westen

**Comment by michaelgiesler** [comment]
CategoryTree-Plugin ist geupdatet, muss eingerichtet werden - siehe issue #192

**Comment by SarahSauer** [comment]
Registrierung funktioniert noch nicht :(

**Comment by Dembelo-Jessica** [comment]
Wenn man das Anmeldeformular abschickt, verursacht das einen "Internal Server Error". Mehr kann ih auch nicht sagen. Ist wohl was falsch konfiguriert.

**Comment by Dembelo-Jessica** [comment]
Registrierung funktioniert
