### ISSUE TITLE
Tutorialtext erweitern

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/projectmanagement#184]
Es soll eine Erklärung für den provokanten Opener geschrieben werden.

**Comment by ghost** [comment]
Das Tutorial wurde allgemein abgeändert und muss nun aktualisiert werden. Vergleiche dazu Dembelo-Cluster im Gattlandrepository: https://github.com/tinagiesler/Gattland/tree/master/Lesecluster/Dembelo
