### ISSUE TITLE
Tutorial korrekturlesen

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/projectmanagement#185]
z.B.:
"Prio­ti­tät"
"zu den Of­fe­nen In­hal­ten"
"von An­de­ren"

**Comment by Dembelo-Jessica** [comment]
Zu "Wassind freie Inahlte" kommt man nur, wenn man oben sagt "Ich hasse Entscheidungen". Ist das Absicht?

**Comment by Dembelo-Jessica** [comment]
Ansonsten: gelesen.

**Comment by SarahSauer** [comment]
Die Verknüpfungen hatte Tina gemacht, aber soweit ich mich erinnere, sollte es so sein

**Comment by Dembelo-Jessica** [comment]
Und jemand sage mir bitte noch, wie ich den Text jetzt wieder in Github kriege.

**Comment by Dembelo-Jessica** [comment]
Für die offene Frage mach ich einen neuen Punkt. GESCHLOSSEN!
