### ISSUE TITLE
Entwicklerflyer ausdrucken

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/projectmanagement#186]
https://github.com/typearea/projectmanagement/blob/master/Flyer/Entwicklerflyer-Entwurf2.pdf

aus Issue #10

**Comment by ghost** [comment]
Ich habe ein Schild gedruckt und gebastelt mit dem Titel des Projekts und 30 farbige Flyer gedruckt

**Comment by ghost** [comment]
Die Anschaffung eines Farbdruckers war eine sehr gute Idee! Das macht solche Aktionen gleich leichter
