### ISSUE TITLE
Tutorial:Erreichbarkeit eines Seitenarms

### ISSUE THREAD

**Issue by Dembelo-Jessica** [typearea/projectmanagement#187]
Zu "Was sind freie Inahlte" kommt man nur, wenn man oben sagt "Ich hasse Entscheidungen". Ist das Absicht?

**Comment by ghost** [comment]
Vorerst Ja. Wird beim Ausbau des Tutorials berücksichtigt.

**Comment by Dembelo-Jessica** [comment]
Dann machen wir dann ein neues Ticket.
