### ISSUE TITLE
Domain für Autorencamp

### ISSUE THREAD

**Issue by Dembelo-Jessica** [typearea/projectmanagement#188]
Richtig du eine Subdomain auf dembelo.de für das Autorencamp ein? autorencamp-essen.dembelo.de oder sowas?

Wenn das erledigt ist, kann die Seite spätestens übermorgen dahin umziehen.

**Comment by michaelgiesler** [comment]
dembelo.de verweist komplett auf 5.9.58.150. Will sagen: Ihr könnte dort beliebige Subdomains konfigurieren.
