### ISSUE TITLE
Finanzierungsseite: Demo-Cluster anpassen

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/projectmanagement#193]
Im Zuge der Entwicklung der "Finanzierungsseite" (https://github.com/typearea/dembelo/issues/230) müssen die Twine-Dateien der Demo-Installation angepasst werden.
Per Definitionem sind Textknoten, die keine weiterführenden Verknüpfungen haben, Finanzierungsknoten, d.h. sie werden gesondert dargestellt, um via Crowdfunding Geld zu sammeln.

**Comment by michaelgiesler** [comment]
Dass ich die Demo-Installation nicht upgrade kann, kostet mich übrigens 12,99€ im Monat.

**Comment by SarahSauer** [comment]
Sofern das nicht nur ein allgemeines Statement, sondern eine Handlungsaufforderung an uns war, bitte ich um "Twine-Dateien für Demo-Installation anpassen für Dummies" ;)

**Comment by ghost** [comment]
ist gemacht für das Democluster
