### ISSUE TITLE
GrünesDesign: Vertipper im Impressum

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#195]
Im letzten Abschnitt des Impressums steht "CC BY-SS 4.0" statt CC-BY-SA 4.0

**Comment by Dembelo-Jessica** [comment]
Das ist richtig so. So heißt es auch auf der offiziellen Seite von Creative Commons und bei iRights. Es steht ja für "(die Lizenz) Creative Commons (wie eine Art Markenname) BY-SA (Unterkategorie)". So wie man schreiben würde "die neue Mercedes C-Klasse", nicht "Mercedes-C-Klasse", oder was auch immer. Das würde ja implizieren, dass es auch eine Peugeaut-C-Klasse etc. gibt.
Nur die Wikipedia weicht da ab, aber das ist nun nicht unbedingt die letzte Instanz für Rechtschreibung.

(Ich erläutere meine Wahl hier nur deshalb so ausführlich, weil ich glaube, dass wir die Frage schon mal hatten und ich hoffe,  meine Recherchen heute ersparen uns allen in Zukunft Verwirrung.)

**Comment by ghost** [comment]
Ja aber die Lizenz heißt "SA" nicht "SS" der Bindestrich ist mir Lumpe :-)

**Comment by Dembelo-Jessica** [comment]
Aaah, stimmt. :) Tja, das hab ich nicht mal jetzt sofort gesehen, als ich schon wusste, wonach ich suche. :D
Ist sofort erledigt.
