### ISSUE TITLE
Patreontext für Spenden Flyer schreiben

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/projectmanagement#2]
Für die Rückseite des Flyers brauchen wir einen Text, der beschreibt wie man bei Patreon für uns spendet.

**Comment by ghost** [comment]
- [x] Jemandem etwas spenden
- [x] Anmeldung mit FB testen
- [x] Tutorial schreiben

**Comment by SarahSauer** [comment]
Ein erster Entwurf. Bitte überarbeiten und Rechtschreibung überprüfen:

Schon ab 1$ im Monat kannst du uns auf der Crowdfuding-Plattform Patreon unterstützen.

Befolge dafür diese vier einfachen Schritte:
1. Melde dich auf patreon.com mit deinem Facebook-Account oder deiner E-Mail-Adresse an.
2. Rufe unsere patreon-Seite unter URL auf und klicke „Become a patron“
3. Wähle die Belohnung aus, die du erhalten bzw. gebe den Betrag ein, den du monatlich spenden möchtest und klicke „Continue“
4. Auf der folgenden Seite kannst du unter Payment deinen Paypal Account verknüpfen und die Spende mit „Confirm and Pledge“ bestätigen. Falls du keinen Paypal-Account hast, kannst du hier auch deine Kreditkarten-Daten eingeben..

Das war es schon! Ab jetzt siehst du auf deinem Dashboard unsere exklusiven Beiträge für Patrons und hast Zugriff auf deine Belohnungen.

**Comment by Dembelo-Jessica** [comment]
Mit ein paar Kleinigkeitenänderungen:

Schon ab 1$ im Monat kannst Du uns auf der Crowdfunding-Plattform Patreon unterstützen.

Das geht in 4 einfachen Schritten:
1.  Melde Dich mit Deinem Facebook-Account oder Deiner E-Mail-Adresse bei patreon.com an.
2. Ruf unsere Patreon-Seite unter URL auf und wähle „Become a patron“.
3. Wähl Deine Belohnung aus, gib den Betrag ein, den Du monatlich spenden möchtest, und drück auf „Continue“.
4. Falls Du ein Paypal-Konto hast: einfach unter "Payment" Deinen Paypal-Account  verknüpfen und die Spende mit „Confirm and Pledge“ bestätigen.
Alternativ kannst Du hier auch Deine Kreditkarten-Daten eingeben.

Das war's schon! Du siehst jetzt auf Deinem Dashboard unsere exklusiven Beiträge für Förderer und hast Zugriff auf Deine Belohnungen.

**Comment by SarahSauer** [comment]
zu 3. Du kannst da auch ohne Belohnung spenden und der Betrag ist an die Belohnung gekoppelt. Alternativvorschlag:
3. Wähl Deine Belohnung aus oder gib den Betrag ein, den Du spenden möchtest, und drück auf "Continue".

**Comment by Dembelo-Jessica** [comment]
Mit ein paar Kleinigkeitenänderungen:

Schon ab 1$ im Monat kannst Du uns auf der Crowdfunding-Plattform Patreon unterstützen.

Das geht in 4 einfachen Schritten:
1. Melde Dich mit Deinem Facebook-Account oder Deiner E-Mail-Adresse bei patreon.com an.
2. Ruf unsere Patreon-Seite unter URL auf und wähle „Become a patron“.
3. Wähl Deine Belohnung aus oder gib den Betrag ein, den Du monatlich spenden möchtest, und drück auf „Continue“.
4. Falls Du ein Paypal-Konto hast: einfach unter "Payment" Deinen Paypal-Account verknüpfen und die Spende mit „Confirm and Pledge“ bestätigen.
Alternativ kannst Du hier auch Deine Kreditkarten-Daten eingeben.

Das war's schon! Du siehst jetzt auf Deinem Dashboard unsere exklusiven Beiträge für Förderer und hast Zugriff auf Deine Belohnungen.
