### ISSUE TITLE
Teilnahme Ausschreibung WirMachenDruck

### ISSUE THREAD

**Issue by SarahSauer** [typearea/projectmanagement#206]
https://www.wir-machen-druck.de/schreibwettbewerb-fantasy-anthologie.html

Jeder bitte einen Text schreiben und einreichen ;)

**Comment by KatharinaMarks** [comment]
Ich habe eh noch unveröffentlichte Kurzgeschichten auf meiner Festplatte liegen, die eigentlich in meinen dritten Kurzgschichtenband aufgenommen werden sollten. Davon kann ich eine auswählen. Wäre gut, wenn jemand Zeit hätte, sie mal auf Wettbewerbstauglichkeit zu prüfen.

**Comment by SarahSauer** [comment]
Ah, das hätte ich genauer ausformulieren sollen. ^^; Idee dahinter ist, durch Texte von uns da unsere Cluster-Inhalte bekannt(er) zu machen. (Das fertige Buch würde auf das LBM 2018 verteilt, was mit unserem geplanten Launch zusammenfiele, also eine gute gratis Werbemaßnahme darstellen würde)

Es sollten also am besten Geschichten sein, die entweder zu Gattland gehören oder in einen neuen Fantasy-Cluster fallen (Gothic Novel würde da ja auch im weitesten Sinne darunter fallen und irgendwie liebäugle ich da schon ein bisschen mit). 
Wobei du da natürlich trotzdem eine deiner Kurzgeschichten nehmen kannst, wenn du die als Ausgang/Teil eines neuen Clusters sehen könntest. Oder wenn du einfach nur für dich selbst gerne da teilnehmen möchtest, ist das natürlich auch kein Problem - hilft uns ja auch, wenn unsere Autoren generell bekannter werden ;)
