### ISSUE TITLE
Design entwickeln

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/projectmanagement#21]
Es soll ein neues Design entwickelt werden.

Seiten:
- Startseite
- Textknotenseite inkl. Metadatenausklapper
- Login inkl. Bestätigungsseite
- Registrierung inkl. eventueller Bestätigungsseiten

**Comment by michaelgiesler** [comment]
Etwaige Vorschläge können in git abgelegt werden.

**Comment by michaelgiesler** [comment]
ohne Footer, siehe dembelo/#201

**Comment by hebestreit** [comment]
@michaelgiesler @tinagiesler erste Layout-Entwürfe sind im Repository unter Design/Layout. Gerne Feedback!

https://github.com/typearea/projectmanagement/commit/7109d7409f168a3510ed89b71a1016ecdc3ac12d

**Comment by michaelgiesler** [comment]
@tinagiesler Bitte gib ihm mal das Logo, von dem du sprachst.

**Comment by ghost** [comment]
feedback im Commit, hier noch die Anfrage, kannst du auch eine Ansicht mit ausgeklapptem Menü machen?

**Comment by hebestreit** [comment]
Ja klar. Ist jetzt im Repository:
https://github.com/typearea/projectmanagement/commit/4ddcafa37031436814614c09cc847289ac848adf

**Comment by ghost** [comment]
ist da : 6662f1f

**Comment by michaelgiesler** [comment]
Können wir intern die Bezeichnung "Schnurrbartzyklop" für das neue Logo prägen? ;-)

**Comment by ghost** [comment]
nein! wir nennen das Logo "das Buch"!

**Comment by ghost** [comment]
Neue Farbauswahl?

Die fände ich gut, in der reihenfolge:
http://www.colourlovers.com/palette/1629780/Winter_in_Madrid
http://www.colourlovers.com/palette/1226197/Sea_of_Poppies
http://www.colourlovers.com/palette/1834804/Haunted_Mouse_RC
http://www.colourlovers.com/palette/2767765/Im_a_BookWorm

oder etwas experimentel:
http://www.colourlovers.com/palette/1970450/Illustrated_Man

Oder langweilig:
http://www.colourlovers.com/palette/2473025/Start-Up

**Comment by michaelgiesler** [comment]
Der aktuelle Stand sieht schon sehr gut aus, ein paar Details können wir schonmal anmerken:
- Abstand außen zu den Kacheln
- kein Abstand zwischen den Kacheln
- Kacheln hochkant
- oben das Logo mit Schrift "WasZuLesen.de"
- Hintergrund nicht weiß
- Textknoten:
  - Blocksatz
  - padding links/rechts größer
  - LinLibertine
  - geringerer Abstand zwischen Absätzen
  - Einrückung erster Zeile eines Absatzes
    - außer erster Absatz oder nach leerem Absatz (da können wir im Vorfeld ein paar css-Klassen setzen)

**Comment by Dembelo-Jessica** [comment]
Was die Farbauswahl angeht, bin ich für warme Töne. Kalt ist nicht so einladend.

**Comment by ghost** [comment]
Es soll http://www.colourlovers.com/palette/1970450/Illustrated_Man werden, wie hier gerade im Gremium beschlossen wurde, experimentel mit #D7C38E als Haupthintergrund und #6A1B1E als Hauptschriftfarbe. Die anderen Farben für Rahmen, Knöpfe und Akzente benutzen damit es gut aussieht.

**Comment by michaelgiesler** [comment]
Da wir jetzt das Lesezeichen- und das Werbefeld rausgeschmissen haben, haben wir in der Höhe genügend Platz, um die Themenfelder in vier Zeilen mit jeweils nur zwei Spalten dazustellen.

**Comment by michaelgiesler** [comment]
@hebestreit Na? Gib mal Laut. ;-)

**Comment by michaelgiesler** [comment]
aktuelles Todo:
- [x] www/web/vendor aus git raus
- [x] bower-Installation im Install-Script einbinden
- [x] bower im Provisioning einbinden
- [x] bootstrap aus composer.json raus
- ...

**Comment by michaelgiesler** [comment]
Der Ist-Zustand ist erstmal in den Master gemergt. Ausreichend, jedoch gibt es für dich bestimmt noch hier und da etwas zu tun. ;-)
