### ISSUE TITLE
Thematische Bewerbung bei der IKF

### ISSUE THREAD

**Issue by SarahSauer** [typearea/projectmanagement#227]
http://www.kreativ-quartiere.de/kuenstlerfoerderung/uebersicht/

bis zum 14.07.17 kann man sich hier noch mit einem Kunstprojekt bewerben - da sollten wir mal zeitnah brainstormen, ob man da unser Romanprojekt oder meinen Coming of Age Cluster einreichen könnte (oder irgendetwas anderes)

**Comment by Dembelo-Jessica** [comment]
Was wir dann vor allem brauchen, ist ein Konzept zur Finanzierung. Wenn wir das Krimiprojekt nehmen würden, bräuchten wir ganz schnell Kooperationen mit zahlender lokaler Gastronomie. Wie viel kann man da wohl reinkriegen? Nicht die ganzen Kosten, oder?

**Comment by ghost** [comment]
Ist abgelaufen, vielleicht nächstes Jahr.
