### ISSUE TITLE
Story App evaluieren

### ISSUE THREAD

**Issue by SarahSauer** [typearea/projectmanagement#228]
Gerade durch den Autorenwelt-Newsletter drauf gestoßen: https://www.autorenwelt.de/blog/storyapp ; https://www.storyapp.de/

Bin das Wochenende über auf der ComicCon, aber vielleicht schafft es von euch einer, sich das bis Dienstag mal genauer anzusehen.

**Comment by Dembelo-Jessica** [comment]
Story App ist im Prinzip eine Anthologiensammlung. 1 000 Kurzgeschichten aus einem Münchener Kurzgeschichtenwettbewerb sind kostenlos zur Verfügung gestellt und nach Themen sortiert.
Also nicht das gleiche, was wir vorhaben.
