### ISSUE TITLE
Termine für Oktober machen

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#29]
Uns gehen die Veranstaltungen aus, die müssen wir im Oktober fortführen.

**Comment by ghost** [comment]
4.10 ist PHP Clean Code

**Comment by ghost** [comment]
die Dienstage sind gebucht.

**Comment by ghost** [comment]
@Dembelo-Jessica @SarahSauer wollen wir in dem Monat sonst noch etwas machen? Der nächste Stammtisch müsste ja auch noch eingetragen werden,  oder?

**Comment by SarahSauer** [comment]
Am 3.10. ist noch der Plotworkshop, der nächste Stammtisch ist schon für den 18.10. eingetragen.
Wir könnten noch eine Diskussionsrunde am 16.10. machen - vielleicht etwas zum Open Content Gedanken?

**Comment by ghost** [comment]
Open Content als Diskussionsthema fände ich sehr gut, am 16.10 ab 17 Uhr wäre es auch machbar, auch wenn das unser Urlaubs WE ist.
