### ISSUE TITLE
FB Veranstaltung für den NaNo Start anlegen

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#30]
Di, 01.11.16    08:00 - 21:00 h     Raum 154    NaNoWriMo Kick-Off! - Gemeinsamer Start in den Schreibmonat
- [x] Kopfgrafik
- [x] Kurzer Text
- [ ] Veranstaltung anlegen

**Comment by SarahSauer** [comment]
Jo, da ich ja jetzt zum November eventuell umziehe, muss ich erstmal schauen, ob ich an dem Tag überhaupt kann _hüstel_ Falls nicht hingen die Zeiten davon ab wann du, @tinagiesler , da sein willst/kannst und müssten ggfs noch angepasst werden. Ich versuche, dass bis Dienstag zu klären (sofern meine Vormieterin bis dahin weiß, wann genau sie auszieht x'D)
Kopfgrafik und Text bereite ich dann schon übers Wochenende vor.

**Comment by SarahSauer** [comment]
Erster Entwurf der Kurzbeschreibung:
Bald ist es wieder soweit! Ab dem 1. November zelebrieren wieder Millionen Autoren weltweit den National Novel Writing Month – ein Schreibmonat, der inzwischen ein internationales Phänomen ist.
Das große Ziel ist es, in einem Monat einen Roman von mindestens 50.000 Worten zu schreiben – ein unvergleichliches Schreiberlebnis. Am 1. November laden wir daher im Unperfekthaus dazu ein, gemeinsam in diesen Monat zu starten.
Das Unperfekthaus bietet für eine Pauschale von 6,90€ eine Getränke-Flat mit warmen und kalten Getränken, damit es immer genug Koffein gibt und niemand beim Schreiben verdurstet. Von unserer Seite aus wird zudem für Motivationsgummibärchen gesorgt ;-)

**Comment by ghost** [comment]
Beschreibung finde ich gut, ich kann ab 9 Uhr da sein, und dann kann es als OpenEnd veranstaltung laufen.

Edit: da es im UPH schon ab 8 Uhr steht, werde ich wohl ab 8 da sein ;-)

**Comment by SarahSauer** [comment]
Ggf. könnten wir die Uhrzeit ja noch ändern ;-) Aber meine Nachbarin meinte jetzt, sie zieht wahrscheinlich erst zum 15.11. um, weil sie noch nichts gefunden hat. Also sollte das problemlos klappen.
