### ISSUE TITLE
Rückblick auf die Schreibwerkstatt

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#31]
Rückblick auf die Schreibwerkstatt schreiben und die Aufgabe veröffentlichen, damit neue Leute mit einsteigen können.

**Comment by SarahSauer** [comment]
ich komm wahrscheinlich das Wochenende nicht dazu - @Dembelo-Jessica magst du das übernehmen?

**Comment by Dembelo-Jessica** [comment]
@SarahSauer Jep

**Comment by Dembelo-Jessica** [comment]
Da fehlt noch ein Datum, schaut mal rein.

**Comment by Dembelo-Jessica** [comment]
Hab's gefunden.

**Comment by SarahSauer** [comment]
Hab den Artikel jetzt für heute nachmittag geplant
