### ISSUE TITLE
Blogartikel

### ISSUE THREAD

**Issue by Dembelo-Jessica** [typearea/projectmanagement#34]
aktuelle Artikel zum Korrigieren

**Comment by Dembelo-Jessica** [comment]
Können wir hier vielleicht irgendwo eine Liste zum Abhaken machen, damit ich markieren kann, was gelesen ist? Da verlier ich sonst den Überblick. Meinetwegen einfach auch in einer Dauer-InArbeit-Karte.

**Comment by Dembelo-Jessica** [comment]
[] Clean Code: 2 offene Anmerkungen in orange, sonst fertig
[x] Rückblick Diskussionsrunde Geldverdienen

**Comment by Dembelo-Jessica** [comment]
Und wie macht man hier verdammte Listen zum Ankreuzen? _heul_

**Comment by ghost** [comment]
1. Listen macht man mit Bindestrich Leerzeichen Eckigeklammer auf Leerzeichen Eckigeklammer zu.
2. Eine Dauer-in-Arbeit-Liste sabotiert das System, Lieber für jeden Artikel ein Issue und das Label "Blogartikel" und dann wie jedes Issue auch hin und her geben, indem man den Bearbeiter ändert und es munter von Ready zu In-Arbeit und zurück verschiebt

**Comment by ghost** [comment]
Ablauf: 
1. Wer eine Idee für einen Artikel hat, schreibt ein Issue unter Backlog
2. Wenn sich einer diesen Artikel gezielt für die nächste Woche vornimmt, trägt er sich als Bearbeiter ein und verschiebt es unter Ready
3. Wenn man dran arbeitet, aber noch nicht fertig ist, steht es unter in-Arbeit
4. Wenn es fertig ist schiebt man es unter Review und ein anderer schaut drüber, dabei kann man in die Kommentare schreiben, ob man erst inhaltliches Feedback braucht oder schon korrigiert werden kann.
5. Wenn der Artikel online geht kann, verschiebt man ihn auf Done.

**Comment by ghost** [comment]
Wird weitergeführt im Issue #36 und entsprechend im Wiki
