### ISSUE TITLE
Clean Code-Blogartikel

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/projectmanagement#35]
typearea/dembelo/#224
Siehe https://www.dembelo.de/wp-admin/post.php?post=524&action=edit

**Comment by Dembelo-Jessica** [comment]
erledigt

**Comment by SarahSauer** [comment]
Von mir euch ein Okay.

**Comment by SarahSauer** [comment]
Wartet auf Veröffentlichung - aktuell zurückgehalten zum Test der Planungsfunktion
