### ISSUE TITLE
Prinzipien für den Umgang mit den Issues dokumentieren

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#36]
Die Ziele für den Umgang mit den Issues und den Ablauf eines Bearbeitungsprozesses dokumentieren, damit wir uns dran halten können und unsere Arbeit immer weiter vergleichbar ist.

**Comment by ghost** [comment]
Ich habe die ersten Vorgaben für den Umgang mit Issues im Wiki hinterlegt: https://github.com/typearea/projectmanagement/wiki/Prinzipien-f%C3%BCr-Issues
@michaelgiesler @Dembelo-Jessica @SarahSauer schaut mal drüber, ob ihr dem bislang so zustimmt und wenn ja versucht es einzuhalten.

**Comment by SarahSauer** [comment]
Bin soweit einverstanden, nur eine Frage hab ich : Es gibt hier ja kein "Review" unter das man es verschieben kann (zumindest sehe ich bei mir keins). Meinst damit das Label "Bitte prüfen"?

**Comment by michaelgiesler** [comment]
@SarahSauer In Waffle.io gibt es nun eine Spalte "Review" - gegebenenfalls mal die Seite neu laden.
In Github wird diese Spalte in der Tat mit dem Label "Bitte prüfen" gesteuert.

**Comment by SarahSauer** [comment]
Okay, im Dembelo-Waffle sehe ich es jetzt auch; beim Project Management wird es nicht angezeigt.

**Comment by michaelgiesler** [comment]
Habe die Spalte nun auch im Projektmanagement hinzugefügt.

**Comment by ghost** [comment]
@Dembelo-Jessica Wie sieht es mit dir aus? soweit angenommen?

**Comment by Dembelo-Jessica** [comment]
jep
