### ISSUE TITLE
Piwik-Statistik geht nicht mehr

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/projectmanagement#39]
Weil irgendjemand dembelo.de auf https umgestellt hat, ohne Piwik zu bedenken.

Unser Piwik-Server benötigt nun ebenfalls ein SSL-Zertifikat, soweit ich weiß.

**Comment by Dembelo-Jessica** [comment]
Welches Zertifikat das bekommt, ist völlig egal. Hauptsache, die Browser akzeptieren das. Kostenlose Zertifikate gibt’s z.B. bei Let’s Encrypt (von denen kommen die Dembelo-Zertifikate) oder bei StartSSL. Für so ein einzelnes manuell eingerichtetes Zertifikat am besten StartSSL, da muss man nicht alle 3 Monate verlängern.

**Comment by michaelgiesler** [comment]
Issue zum Einbinden eines StartSSL-Zertifikats: #41

**Comment by michaelgiesler** [comment]
piwik.waszulesen.de läuft nun über https. Sobald hier wieder Besuche erfasst werden, kann dieses Issue geschlossen werden.
