### ISSUE TITLE
Verweis auf die FBGruppe für Flyerrückseite

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#4]

**Comment by ghost** [comment]
Mein ganz schlichter Vorschlag wäre:

---

Wer unser Projekt weiter beobachten möchte kann dies …

... bei Facebook: https://www.facebook.com/Dembelo/
... oder dank Newsletter: https://www.dembelo.de/newsletter/ 

Ihr könnt aber auch mit uns diskutieren, organisieren und zu unseren Veranstaltungen im Unperfekthaus kommen, dazu meldet euch in unserer Facebookgruppe an:
https://www.facebook.com/groups/dembelo/ 

---

Bitte Feedback, Rechtschreibung korrigieren und ins Flyerlayout einpassen.

**Comment by Dembelo-Jessica** [comment]
Wer unser Projekt weiter beobachten möchte kann dies …

... bei Facebook: https://www.facebook.com/Dembelo/
... oder per Newsletter: https://www.dembelo.de/newsletter/

Ihr könnt aber auch mit uns diskutieren, organisieren und zu unseren Veranstaltungen im Unperfekthaus kommen. Dazu meldet euch einfach in unserer Facebookgruppe an:
https://www.facebook.com/groups/dembelo/

**Comment by SarahSauer** [comment]
Schlicht ist gut – gefällt mir. Passt von der Länge auch gut auf den Flyer.
