### ISSUE TITLE
Wie legt man Ordner im repository an?

### ISSUE THREAD

**Issue by SarahSauer** [typearea/projectmanagement#49]
Ich würde gerne einen Ordner für die FB Kopfgrafiken anlegen, finde aber nicht heraus, wie ich das bewerkstelligen soll :(

**Comment by michaelgiesler** [comment]
Entweder mit einem git-Client oder - etwas umständlich - über die github-Oberfläche.
Letzteres geht über den Button "Create new file". Wenn man dort als Dateiname einen Slash benutzt, erkennt github dies korrekt als Verzeichnis. Da man dann aber wirklich eine Datei anlegen muss, schlage ich als Konvention vor, in jedem Verzeichnis eine Datei mit dem Namen "README.md" anzulegen, in der kurz erklärt wird, was es mit den Dateien des Ordners auf sich hat.

**Comment by SarahSauer** [comment]
Danke - ich probiere es gleich mal aus!
