### ISSUE TITLE
Texte in den Werbeflyer Autorencamp einsetzen

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#51]
Das Barcamp am Samstag

Im großen Kaminzimmer des Unperfekthauses in Essen findet am Samstag von 15:00 bis 24:00 Uhr das Autorencamp im Modell eines Barcamps statt. Also als offene Tagung mit spontanen Workshops und Diskussionsrunden von Autoren für Autoren. Alles rund um das Thema kreatives Schreiben und Veröffentlichung. 
Teilnahme ist auch spontan möglich und kostet 11,90€, was dem Eintirtt des Unperfekthauses entspricht und alle alkoholfreien Getränke warm und kalt enthält.

Die nächtliche Schreibwerkstatt 

Gemeinsames Schreiben im WG-Hotel des Unperfekthauses: Die Hotelsuite bietet 14 Betten in Doppelzimmern,viele Bäder und eine große Gemeinschaftsküche mit Tisch. Hier können 14 gebuchte Teilnehmer übernachten und die Nacht gemeinsam durchschreiben. 
Teilnahme nur nach verbindlicher Buchung. Die Übernachtung im WG-Hotel (Bett im Dopplezimmer), mit Barcamp am Samstag und Brunch am Sonntag kostet 75€ pro Person. 
Teilnahme ab 18!
Buchung unter: LINK

**Comment by SarahSauer** [comment]
Ich hab den Text noch leicht abgeändert, damit er in beiden Spalten ungefähr gleich lang ist:
Das Barcamp am Samstag

Im großen Kaminzimmer des Unperfekthauses in Essen findet am Samstag von 15:00 bis 24:00 Uhr das Autorencamp im Modell eines Barcamps statt. Also als offene Tagung mit spontanen Workshops und Diskussionsrunden von Autoren für Autoren. Alles rund um das Thema kreatives Schreiben und Veröffentlichung. 
Teilnahme ist auch spontan möglich und kostet nur den Eintritt ins Unperfekthaus. 
(Entweder 6,90€ inkl. warmer und kalter Getränke für den ganzen Tag oder 11,90€, wenn ihr das Haus zwischendurch verlassen und wiederkommen wollt)

Die nächtliche Schreibwerkstatt

Gemeinsames Schreiben im WG-Hotel des Unperfekthauses: Die Hotelsuite bietet 14 Betten in Doppelzimmern, viele Bäder und eine große Gemeinschaftsküche mit Tisch. Hier können 14 gebuchte Teilnehmer übernachten und die Nacht gemeinsam durchschreiben. 
Teilnahme nur nach verbindlicher Buchung. Die Übernachtung im WG-Hotel (Bett im Doppelzimmer), mit Barcamp am Samstag und Brunch am Sonntag kostet 75€ pro Person. 

Teilnahme ab 18!

Buchung unter: 
http://bit.ly/autorencamp2017

**Comment by Dembelo-Jessica** [comment]
Nur eine kleine Änderung. Ich hoffe, es passt trotzdem in die Spalte wie gewünscht. Ich hab versucht, es an anderer Stelle auszugleichen.

Das Barcamp am Samstag

Im großen Kaminzimmer des Unperfekthauses in Essen findet am Samstag von 15:00 – 24:00 Uhr das Autorencamp nach dem Modell eines Barcamps statt, also als offene Tagung mit spontanen Workshops und Diskussionsrunden von Autoren für Autoren. Alles rund um das Thema kreatives Schreiben und Veröffentlichung.
Teilnahme ist auch spontan möglich und kostet nur den Eintritt ins Unperfekthaus.
(Entweder 6,90€ inkl. warmer und kalter Getränke für den ganzen Tag oder 11,90€, wenn ihr das Haus zwischendurch verlassen und wiederkommen wollt.)

Die nächtliche Schreibwerkstatt

Gemeinsames Schreiben im WG-Hotel des Unperfekthauses: Die Hotelsuite bietet 14 Betten in Doppelzimmern, viele Bäder und eine große Gemeinschaftsküche mit Tisch. Hier können 14 gebuchte Teilnehmer übernachten und die Nacht gemeinsam durchschreiben.
Teilnahme nur nach verbindlicher Buchung. Die Übernachtung im WG-Hotel (Bett im Doppelzimmer), mit Barcamp am Samstag und Brunch am Sonntag kostet 75€ pro Person.

Teilnahme ab 18!

Buchung unter:
http://bit.ly/autorencamp2017

**Comment by SarahSauer** [comment]
Ja, das passt so auch noch - nur was mir gerade auffällt: Müsste es nicht "Alles rund um die Themen kreatives Schreiben und Veröffentlichung." heißen (und fällt uns da vielleicht noch was drittes ein? -Dann wären die beiden Spalten gleich voll _hüstel_)

**Comment by Dembelo-Jessica** [comment]
Ja, eigentlich hast du recht, lieber Plural.

Vllt. kreatives Schreiben, Überarbeitung und Veröffentlichung? Oder, je nachdem, was ihr machen wollt, Schreiben, Veröffentlichung und Marketing? Was war so euer Plan?

**Comment by SarahSauer** [comment]
Oh, das mit Marketing passt gut – inhaltlich hatten wir bisher noch keine so detaillierten Plan aufgestellt, aber Marketing ist ein so wichtiges Thema, dass wir das auf jeden Fall auch anschneiden werden.
