### ISSUE TITLE
Blogartikel zum Plot-WS

### ISSUE THREAD

**Issue by Dembelo-Jessica** [typearea/projectmanagement#54]

**Comment by Dembelo-Jessica** [comment]
Kurze Zusammenfassung als Lebenszeichen im Blog

**Comment by SarahSauer** [comment]
Mein Kreislauf hat mich gestern verlassen (= ich bin auf Arbeit zusammengeklappt …). Ich lieg jetzt mit Schwindel und Übelkeit im Bett, daher weiß ich nicht, ob ich es noch vorm Umzug&Nano schaffe, den Artikel abzuschließen :-/

**Comment by Dembelo-Jessica** [comment]
Ich kümmer mich drum. Gute Besserung!
