### ISSUE TITLE
dembelo.de mit youtube verknüpfen

### ISSUE THREAD

**Issue by SarahSauer** [typearea/projectmanagement#55]
Damit wir von unseren Videos aus auf unsere Website verlinken können, muss die Website bestätigt werden

https://www.youtube.com/advanced_settings

**Comment by michaelgiesler** [comment]
Bei dem Link bin ich in meinem eigenen Youtube/Google-Konto, was dem dembelo-Youtube-Kanal ja nicht hilft.

Was muss denn zur Bestätigung getan werden?

**Comment by SarahSauer** [comment]
Ja, damit der Link funktioniert, muss man mit dem dembelo-Konto eingeloggt sein.

Am einfachsten wäre wohl eine html Datei auf dembelo.de hochzuladen. Aber gibt noch andere Möglichkeiten: https://support.google.com/webmasters/answer/35179

**Comment by Dembelo-Jessica** [comment]
@SarahSauer Ich kann mich bei youtube nicht einloggen. Da werde ich immer auf irgendeine schwachsinnige Seite umgeleitet, wo ich meine Identität bestätigen soll. Kannst du mir den html-Text, der auf dembelo.de soll, hierher kopieren? Dann füge ich den ein.

**Comment by SarahSauer** [comment]
@Dembelo-Jessica Hat etwas gedauert, aber hab dir die Seite jetzt per Mail geschickt

**Comment by Dembelo-Jessica** [comment]
@SarahSauer Ist eingefügt. Probier mal jetzt.
