### ISSUE TITLE
Jingle und Intro für YouTube Channel

### ISSUE THREAD

**Issue by SarahSauer** [typearea/projectmanagement#6]
- [x] Musik für Jingle raussuchen
- [x] Intro Text überlegen
- [x] Intro Titel-Hintergrund 
- [x] Alles aufnehmen

**Comment by SarahSauer** [comment]
In einer ersten Fassung erledigt, bin aber noch nicht ganz zufrieden - fürs erste Video reicht es aber. Wenn wir weniger perfekt sind, ist das ja auch sympathisch.

**Comment by ghost** [comment]
und passend zum UNperfekthaus

**Comment by Dembelo-Jessica** [comment]
Gibt es eine Möglichkeit, sich das schon mal anzuhören? Bin neugierig. :) Vllt. Link über DB?

**Comment by SarahSauer** [comment]
Gestern nicht mehr gesehen, da ich meinen Mac in Ruhe hab arbeiten lassen, während ich etwas gelesen habe x'D Das gesamte Video war nach dem ersten Umwandelversuch stolze 15GB und musste gestern erstmal nochmal neu umgewandelt werde und das kleinere Video (immer noch stolze 2GB+) hat dann bist heute morgen gebraucht, hochzuladen und von youtube verarbeitet zu werden. Hier der Link: https://youtu.be/Z4CdhVNLVKI (wir können uns gerne am Di dann nach einem anderen Jingle umsehen und am Text feilen - ich hatte Donnerstag nach 3+ Stunden Schneidearbeit aber einfach keinen Nerv mehr dafür x'D)
