### ISSUE TITLE
"Home" als Seitentitel ändern

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/projectmanagement#65]
www.dembelo.de hat derzeit "Home" als Seitentitel. Aus verschiedenen Gründen sollte der zu etwas aussagekräftigerem geändert werden.

**Comment by Dembelo-Jessica** [comment]
Bitte aussagekräftigen Vorschlag, dann änder ich das.

**Comment by ghost** [comment]
Einfach nur zu "Dembelo" mehr sieht man da eh nicht
