### ISSUE TITLE
Verlängerungskabel für den 1.11. organisieren,

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#66]
... damit auch innen gelegene Tische gut mit Strom versorgt werden können.

**Comment by ghost** [comment]
Ich habe zwei 5m Kabel für 10 € angeschafft. Dazu haben wir einen dreierstecker. @SarahSauer  hast du einen weiteren mehrfachsteckere im UPH?

**Comment by SarahSauer** [comment]
Ich hab noch einen Dreierstecker und eine Verlängerungsschnur im UPH, kann aber auch noch einen Mehrfachstecker mitbringen.
