### ISSUE TITLE
Blogartikel Schreiben mit Vorstrukturierung

### ISSUE THREAD

**Issue by Dembelo-Jessica** [typearea/projectmanagement#70]
Am Ende des artikels zum Plot-Workshop habe ich eine Ankündigung angehängt, dass Tina ihre Ergebnisse mitteilen wird, zu dem, was sie im Plot-WS gelernt hat.

**Comment by ghost** [comment]
@Dembelo-Jessica bitte korrigieren
@SarahSauer kannst du dazu eine Kopfgrafik bauen? 

Danke!

**Comment by Dembelo-Jessica** [comment]
@tinagiesler Da ist noch ein Wort rot markiert. Scheint das falsche zu sein, ich versteh nicht ganz, was Du sagen willst. Probier mal ein anderes!
