### ISSUE TITLE
Daedalic eruieren

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/projectmanagement#71]
"Das auf interaktive Literatur, Charakter- und Story-gesteuerte Spiele spezialisierte Hamburger Studio Daedalic Entertainment [...]"

Das klingt, als könnten sie für uns interessant sein.

Artikel auf Prolinux: http://www.pro-linux.de/news/1/24180/abenteuerspiel-silence-erschienen.html

Firma dahinter: http://www.daedalic.de/de/About/

**Comment by ghost** [comment]
@Dembelo-Jessica Kannst du das mal sichten und nach einer Schnittstelle Suchen wie die von uns und wir von denen profitieren könnten?

**Comment by ghost** [comment]
Ging ein in: https://github.com/typearea/projectmanagement/wiki/Potenzielle-Kooperationen
Sowie issue #96 und issue #97
