### ISSUE TITLE
Rollenspiele noch mal aufgreifen für Schreibprozess

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#73]
Was können wir aus Rollenspielen allgemein und aus Onlinerollenspielen im besonderen. 

ggf. einen Artikel daraus machen.

**Comment by ghost** [comment]
Habe Kathis Artikel gerade in den Blog kopiert, kann aber weder drüberlesen gerade noch Korrigieren. @Dembelo-Jessica kannst du bitte?
Eine Kopfgrafik wäre auch gut.

**Comment by Dembelo-Jessica** [comment]
Graphik muss jemand anders machen, gerade keine Zeit.

@KatharinaMarks Zum Artikel:
1. Ist "gegengleichen" als Verb zu "gegengleich" gemeint? Also etwas spiegelverkehrt machen? Ist mir unklar, was an der Stelle genau gemeint ist.
2. Der Input verschiedener Autoren trägt […] akuter zum Plotverlauf bei […]
-> akuter? Im Sinne von "unmittelbarer"? Versteh ich nicht, vllt, ist ein adneres Wort besser?
3. Der rot markierte Satz im Fazit: Bezug ab "dass" ist etwas unklar. Satz umdrehen? Oder was soll es heißen?

P.S.: Hallo und willkommen im Team! :)

**Comment by KatharinaMarks** [comment]
1. 'abgleichen' ist vielleicht sinnvoller.
2. akuter im Sinne von direkter
3. ersetze 'dass' durch 'indem', vielleicht wird es dann deutlicher?
