### ISSUE TITLE
Kein Zugriff auf WP-Admin

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#78]
Ich habe seit kurzem keinen Zugriff mehr auf das Backend des Blogs, bekomme nur Fehler 401 Unauthorized. Kekomme aber keinen Login.

**Comment by Dembelo-Jessica** [comment]
Dein Browser fragt aus irgendwelchen Gründen nicht nach dem Passwort. Starte mal den Browser neu und wenn es nicht hilft, geh auf folgende Adresse: 
https://Dembelo@www.dembelo.de/blog/wp-login.php?redirect_to=https%3A%2F%2Fwww.dembelo.de%2Fblog%2Fwp-admin%2F&reauth=1
Dann muss er eigentlich fragen.

**Comment by ghost** [comment]
Lag am zu lang laufenden Browser, nach Neustart geht alles wieder, Danke!
