### ISSUE TITLE
Startup-Wettbewerbe und Förderungen recherchieren

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/projectmanagement#80]
Es soll im Wiki eine Liste von Startup-Wettbewerben und Kultur- und Bildungsförderungen erstellt werden.

In welchem Zeitrahmen finden sie statt? Wie sind die Anforderungen/Aufwand? Wie der Nutzen?

**Comment by ghost** [comment]
https://www.bezreg-arnsberg.nrw.de/themen/r/regionale_kulturpolitik_ruhrgebiet/index.php

**Comment by michaelgiesler** [comment]
ein paar Links:
- https://foerderprogramme-deutschland.de
privates Unternehmen, berät
- KfW
- http://www.existenzgruender.de
  Bundesministerium für Wirtschaft und Energie
- http://www.existenzgruender.de/DE/Weg-in-die-Selbstaendigkeit/Finanzierung/Foerderung/Wichtige-Foerderprogramme/inhalt.html
  Liste und Infos
- http://www.startercenter.nrw.de/
- https://www.bezreg-arnsberg.nrw.de/themen/r/regionale_kulturpolitik_ruhrgebiet/index.php
- https://www.kbg-nrw.de/de/home
  Kapitalbeteiligungsgesellschaften
- http://deutscher-literaturfonds.de
- https://www.essen.de/kultur_und_bildung/kulturbuero/kulturfoerderung/f_rderung_der_zentralen_und_bezirklichen_kulturarbeit.de.html

**Comment by michaelgiesler** [comment]
Habe die Links mal ins Wiki kopiert: https://github.com/typearea/projectmanagement/wiki/Gr%C3%BCndungswettbewerbe
