### ISSUE TITLE
Slot auf Frankfurter Buchmesse vorbereiten

### ISSUE THREAD

**Issue by michaelgiesler** [typearea/projectmanagement#83]
Es sollen vorhandene Kontakte genutzt werden, um einen Slot auf der Frankfurter Buchmesse im Oktober 2017 zu bekommen.
Dieser Slot muss dann entsprechend vorbereitet werden.

**Comment by michaelgiesler** [comment]
Sara entscheidet, ob. Wenn nein => obsolet

**Comment by ghost** [comment]
Nicht mehr relevant
