### ISSUE TITLE
Rechtlichen Hintergrund klären (allgemein)

### ISSUE THREAD

**Issue by SarahSauer** [typearea/projectmanagement#87]
Kommentar von Tina dazu im Trello: Kaufhinweis: 4. Kaufhinweis vor den Optionen muss konzipiert und rechtlich bestätigt sein
5. Der Geldfluss muss analysiert und rechtlich geprüft sein
6. Bedingungen und Organisation der Vorfinanzierung muss geklärt sein

**Comment by KatharinaMarks** [comment]
sprich: Auswertung Businessplan.
