### ISSUE TITLE
Konzept für Social Media Marketing

### ISSUE THREAD

**Issue by SarahSauer** [typearea/projectmanagement#90]
- [x] Facebook Gruppe
- [x] Facebook Seite
- [x] Twitter
- [x] Instagram
- [x] Pinterest

**Comment by ghost** [comment]
Siehe Issue #106 – ein solches Blogkonzept vernetzt uns unter anderen Blogs und Bezieht Infos aus dem SMM und dtreut da auch hin.

**Comment by ghost** [comment]
PS.: Kannst du das Konzept im Projektmanagement Wiki dokumnetieren? Muss kein langer Text sein, ein paar Grundkontepte und Vorgaben würden reichen.

**Comment by SarahSauer** [comment]
Meine Gedanken zum Social Media Konzept hab ich hier vermerkt - https://github.com/typearea/projectmanagement/wiki/Konzept-f%C3%BCr-Social-Media-Marketing
