### ISSUE TITLE
Teamzuwachs bloggen

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#95]
Unser neuers Teammitglied sollte kurz vorgestellt werden und sich auch kurz zu Wort melden, damit die Welt weiß, dass wie wachsen.

**Comment by KatharinaMarks** [comment]
Ich könnte einen kurzen Vlog beitragen, der in den Blogpost eingebettet werden kann.

**Comment by ghost** [comment]
Sehr coole Idee!

**Comment by Dembelo-Jessica** [comment]
Artikel ist für morgen geplant.

Zur Info für die Zukunft: Videos im wav-Format funktionieren nicht, bitte mp4 verwenden. Ein neues Plugin war also unnötig. ;)
