### ISSUE TITLE
Präsentationsmappe

### ISSUE THREAD

**Issue by ghost** [typearea/projectmanagement#96]
Um mit Presse, Verlagen oder Firmen sprechen zu können bräuchten wie eine Mappe, die in Form einer "Bewerbung" aufgebaut ist, da gelassen werden kann und mit schönen Bildern und Schautafeln erklärt was wir machen. Die kann man im Gespräch zur untermalung nutzen und als Werbung da lassen.

**Comment by michaelgiesler** [comment]
wurde als obsolet erkannt
